name: Continuous Integration

on:
  push:
    paths-ignore:
      - 'documentation/**'
      - 'README.md'
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build --target test --tag todo-app:test .
      - run: docker run --env-file .env.test todo-app:test

  publish:
    name: Publishing
    runs-on: ubuntu-latest
    needs: build
 #   if: github.event_name == 'push' && github.ref == 'main'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}

      - uses: actions/checkout@v2
      - run: docker build --target production --tag todo-app:prod .
      - run: docker push paulcurren/devops-course-starter:production
