name: Continuous Integration

on:
  push:
    paths-ignore:
      - 'documentation/**'
      - 'README.md'
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build --target test --tag todo-app:test .
      - run: docker run --env-file .env.test todo-app:test
 
  azure-deploy:
    name: deploy to Azure
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: docker build --target production --tag paulcurren/todo-app:prod .
      - run: docker push paulcurren/todo-app:prod

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: Cohort22_PauCur_ProjectExercise 
          dns-name-label: pdc-todo-app
          image: paulcurren/todo-app:prod
          name: pdc-todo-app-container
          location: 'uk south'
          ports: 8000
          environment-variables: FLASK_APP=todo_app/app:create_app() FLASK_ENV=production 
          secure-environment-variables: SECRET_KEY=secret-key TRELLO_KEY=${{ secrets.TRELLO_KEY }} TRELLO_SECRET=${{ secrets.TRELLO_SECRET }} TRELLO_TOKEN=${{ secrets.TRELLO_TOKEN }} TRELLO_USERNAME=${{ secrets.TRELLO_USERNAME }} TRELLO_BOARDID=${{ secrets.TRELLO_BOARDID }}
