name: Continuous Integration

on:
  push:
    paths-ignore:
      - 'documentation/**'
      - 'README.md'
#  pull_request:
#    branches:
#      - main

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build --target test --tag todo-app:test .
      - run: docker run --env-file .env.test todo-app:test

  publish:
    name: Publishing
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'xxx' && github.ref == 'main'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}

      - uses: actions/checkout@v2
      - run: docker build --target production --tag paulcurren/todo-app:prod .
      - run: docker push paulcurren/todo-app:prod

  heroku-publish:
    name: Publishing to Heroku
    runs-on: ubuntu-latest
    needs: build
    #if: github.event_name == 'xxx' && github.ref == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.17
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: pdc-todo-app
          dockerfile_path: ''
          options: '--target production --tag paulcurren/todo-app:prod'
          formation: '' 
